version: '3.3'

services:
  backend:
    build:
      context: backend/
      dockerfile: Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=mahsa.settings.docker-compose
    ports:
      - "8000:8000"
      - "9001:9001"
      - "5555:5555"
    depends_on:
      - redis
    volumes:
      - "./backend/shared:/app/shared"

  nginx:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"