# Generated by Django 4.2.3 on 2023-07-12 14:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Config',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('protocol', models.CharField(max_length=255)),
                ('hash', models.CharField(max_length=32)),
                ('base64', models.TextField()),
                ('ads', models.TextField()),
                ('created_at', models.DateTimeField()),
                ('edited_at', models.DateTimeField()),
                ('expired_at', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hash_config', models.CharField(max_length=255)),
                ('client_ip', models.CharField(max_length=255)),
                ('subnet_ip', models.CharField(max_length=255)),
                ('reported_at', models.DateTimeField()),
                ('ping_ms', models.IntegerField()),
                ('fragment_switch', models.BooleanField()),
                ('cdn_ip', models.CharField(max_length=255)),
                ('ads_report', models.BooleanField()),
                ('user_rating', models.IntegerField()),
                ('app_version', models.CharField(max_length=255)),
                ('os_type', models.CharField(max_length=255)),
                ('os_version', models.CharField(max_length=255)),
                ('config', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='configs', to='app.config')),
            ],
        ),
    ]
