# Generated by Django 4.2.3 on 2023-07-19 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='config',
            name='num_consumed',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='config',
            name='xray_score',
            field=models.FloatField(null=True),
        ),
    ]
